version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    build: ./Front
    ports:
      - "3000:80"
    depends_on:
      - backend